name: Build Compose Desktop

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string
permissions:
  contents: read
#  id-token: write
env:
  version: ${{ inputs.version || '1.0.0' }}
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./client-gui/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageReleaseDistributionForCurrentOS --project-prop appVersion=${{ env.version }}
          build-root-directory: client-gui/
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-package
          path: client-gui/build/compose/binaries/main-release/*/*.*
          if-no-files-found: error
