name: Build Compose Desktop

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      os:
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      os:
        required: true
        type: string
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'
permissions:
  contents: read

env:
  version: ${{ inputs.version || '0.0.0' }}
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./clients/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: superReleaseBuild -PappVersion=${{ env.version }}
          build-root-directory: clients/
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.os }}-package
          path: |
            clients/build/jpackage/*/*.*
          if-no-files-found: error
