name: Create Release Draft Compose Desktop

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'vX.X.X'
        required: true
        type: string
env:
  version: ${{ inputs.version || github.ref_name }}
permissions:
  contents: write
#  id-token: write
jobs:
  build:
    if: startsWith(env.version, 'v')
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    uses: ./.github/workflows/build-compose.yml
    with:
      version: ${{ env.version }}
      os: ${{ matrix.os }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./out
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: (Draft) Release ${{ env.version }}
          draft: true
          files: ./out/*/*/*.*
