name: Create Release Draft Compose Desktop

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
permissions:
  contents: write
#  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build-compose.yml
    with:
      version: ${{inputs.version}}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: ./out
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: (Draft) v${{inputs.version}}
          draft: true
          files: ./out/*/*/*.*
