name: Build Compose Desktop

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
#  id-token: write

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageReleaseDeb
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          # Path of the directory containing the static assets.
          path: build/compose/binaries/main-release/deb/eselinux_1.0.0-1_amd64.deb
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: packageReleaseMsi
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/compose/binaries/main-release/msi/EseLinux-1.0.0.msi